codecov:
  notify:
    after_n_builds: 3

comment:
  require_changes: true
  layout: "diff, files"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch: off
