comment:
  require_changes: true
  layout: "diff, files"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch: off

flags:
  wheels:
    carryforward: true
  pillow-dev:
    carryforward: true
  import-error:
    carryforward: true
